### ISSUE TITLE
Remover os clientes ACME e XYZ

### ISSUE THREAD

**Issue by fabriciofx** [fabriciofx/aula-ta#2]
Os clientes **ACME** e **XYZ** não são mais nosso clientes. Precisam ser removidos.

**Comment by rupertcoder** [comment]
Mande mais informações pq estes clientes vão ser removidos.

**Comment by fabriciofx** [comment]
São removidos pq não pagaram mais as mensalidades.

**Comment by rupertcoder** [comment]
Certo. Estas mudanças vão afetar o ClientesDao?

**Comment by fabriciofx** [comment]
@rupertcoder Não vai alterar os DAOs.

**Comment by rupertcoder** [comment]
Certo, @fabriciofx. Mas você disse isso:

> Mande mais informações pq estes clientes vão ser removidos.

Mesmo assim, não vai mexer nos DAOs?

**Comment by fabriciofx** [comment]
Sim, @rupertcoder. Prevalece o que foi dito.
